* Обсуждение
** Trace preserving выполняется для всех axiomatic memory models
** Performance моделей. Стоит как-то более явно обсуждать его в таблице/статье. Как?
* Задачи
** TODO В future work упомянуть NVM модели и модели файловых систем 
* Комментарии ДВ
** (Антон/Женя) Intro: Сколько статей появляется каждый год на (major) conferences (DBLP).
пока там слишком формально в одном месте цитируется 15 работ.

(Антон) HELP. Нужна помощь. Что-то я с наскока не понял, как по keywords искать в DBLP.

** [DONE] 1. Related work - мало.
Тут под видом related work можно было бы дать более широкий разворот существующей картины исследований, тенденций и показать,
что назрела необходимость обозрить programming languages weal memory models.
При этом во введении объясняется, что есть слабые модели памяти и мотивируется, что нужен какой-то общий обзорный труд про них.
Так дайте же в related works некоторую перспективу исследований в этой области. Еще раз повторюсь, чтобы показать, что есть что описывать.
*** (Anton) Решение
Related work:
Динамика развития: SC (1989), Java (2005), C11 (2011), Promising (2017), Weakestmo (2019).
Появляются новые модели.
Проблемы: [Boehm-Demsky:MSPC14, Batty-al:ESOP15].

Добавить пару абзацев про то, что существуют разные модели/подходы --- в некотором смысле сжатый вариант раздела 6.
Упомянуть работы, которые ставят проблемы моделей памяти для языков программирования:
[Boehm-Demsky:MSPC14, Batty-al:ESOP15].
** [DONE] 2. В методологии reseach question выглядит голо.
Нет объяснений и даже попыток их дать. "Это так" - пишет автор. И дальше поясняет, что это означает.
А к чему это так, почему обзор удобно строить вокруг этого question - остается загадкой.
Ну и дальше, до описания процедуры, все как-то несвязно – предлагается читателю самому, изнутри области, связывать заявления автора.
А необходимо все называть явно, пробрасывать мостики явно.    
*** (Женя) Решено
Убрать первое предложение и первый research question. (Чуток меняем второй абзац.)

Синтаксическая связь между 3 критериями (С1, С2, С3 и др.) и дальнейшими разделами.
Такое же название, как и у criteria (мб переименовать criteria) и поменять форму (не вопросы).
** 3. «10 peer-reviewed research papers [2, 5–7, 9, 12–16]
   whose main contribution was a proposal of a new PL weak memory model.» - это недостаточная и не та мотивация, как мне кажется.
   Вот если сказать, что они взяты с PLDI и POPL, и предлагают новые модели памяти, то это выглядит солиднее.
*** (Женя) Решение
Добавить, что статьи на PLDI и POPL (и OOPSLA) -- major conferences on PL.
Акцент на то, что это не все статьи из области с этих конференций.
** [DONE] 4. Далее, keyword phrases лучше дать через запятую, не булетами. Помпезно и излишне раздуто выглядит.
   И, кстати, Женя, Вам это свойственно в данной статье. (у меня сходное впечатление от начала раздела про Методологию).    
*** Решено 
(Антон) Мне больше нравится так, как есть. Не вижу проблемы.
** [DONE] 5. Название раздела 4 «Criteria for Memory Models». Я не уверен в своем английском, но так говорят?
   Кретерий выбора, критерий чего-то (в смысле для чеого-то).
   А тут, по мне, лучше выглядело бы что то из этого списка «characteristics», «properties», «features».
*** Комментарий
(Антон) Criteria -- множественное число. В таком варианте нравится больше, чем предложенные варианты.
*** (Женя) Решено
Поправить, чтобы была связь с methodology
** 6. Более того, не объясняется, что это за феномен – критерий, и зачем он нужен. А сразу говорится, какие они, и поскакали в глубину.
   Нельзя сказать что-то вроде того, что речь идет об основных характеристиках слабых моделей, зачем нам нужны эти характеристики.
   Ну и дальше, что мы в качестве таковых выбрали вот такой список.
   И обязательно  объяснить, почему мы выбрали именно их. И получится более объемный текст в начале раздела.
   А то выходит, Женя, что Вы как-то формально отнеслись к своему предложению такие введения писать в начале каждого раздела.    
*** Комментарий
  Тут опять сказать, что модели балансируют между гарантиями и оптимизациями. 
  Мы рассматриваем критерии, которые позволяют оценить модель с точки зрения гарантий и разрешенных оптимизаций.
  Упомянуть, что традиционно оптимизации также разделяют на те, что выполняются железом и компилятором. 
  Первые ведут к критерию оптимальности схемы компиляции, вторые к корректности трансформаций. 
  Все рассматриваемые критерии стандартны и встречаются в выбранных нами статьях (иногда с немного отличающейся терминологией),
  а не придуманы нами. 

** 7. Можно, кстати,  прямо здесь дать отдельную табличку с этими критериями – у них же есть подкритерии!
   А то нефига не дружественно для читателя получается – Вы сразу его окунаете в детали, и нет места,
   где все собрано вместе (с мотивацией и общими объяснениями) про эти критерии.
*** Комментарий
  Такая табличка будет дублировать заголовок таблиц 1 и 2
*** (Женя) Решение
Добавить табличку со всеми критериями. Придумать решение
** 8. В разделе 5, в начале, я нашел очень хороший объясняющий текст (редкость, кстати, в нашей статье!):
«A particular challenge of this comparison was the fact that consulted
research papers often use different terminology,
have incomplete information about models, and
sometimes they even contradict each other.»
 
Так вот, предлагаю перенести его во введение. А то там как-то пусто в смысле отточености мотивации.
Нет обзоров и все… Ну а здесь парой слов восстановить это контекст и двигаться дальше.
** 9.  Порядок, в котором классы моделей упоминаются в первый раз в разделе 5,
   порядок следования этих классов в таблице и порядок соответствующих подразделов в разделе 6 ДОЛЖНЫ СОВПАДАТЬ!
   А сейчас они не совпадают…

** 10. Классов 6, а подразделов в разделе 6 – семь штук! Это все надо очень четко объяснять во введении к разделу.
*** Комментарий
  Так вроде бы это есть, последний параграф во введении к разделу Analysis объясняет назначение подсекции 6.7
** 11. Во введении к разделу 6 есть странный текст
«Note that we present the classes in different order
compared to the order in tables 1 and 2. It is
because we wanted to first discuss the problem
of thin-air values (§6.3) and then describe various
solutions of this problem (§6.4 to §6.6).»
 
Все запутывает. В целом, это введение надо начинать со структуры, а не с объяснений. Вот уже второе предложение этого введения должно отвечать на вопрос, почему разделов 7 а не 6.   
 
Структура у Вас Женя, тонко не проводится по тексту, но частенько теряется в объяснениях.
*** Комментарий
  Можно переформулировать, чтобы текст отталкивался от структуры. По поводу того, что порядок разделов отличается 
  от порядка классов в таблице. Вроде как это было сознательно сделано и согласовано, чтобы сначала обсудить проблему OOTA а потом 
  уже объяснить как разные классы моделей подходят к решению этой проблемы. 
** 12.  В разделе 7 надо явно сказать, что мы лезем внутрь классов. Почему не говорите этого явно, прямо в первом предложении?
*** (Женя) Решение
Добавить
** 13. Женя, предлагаю тест. Вытащите все введения к разделам в отдельный файл, пустите их подряд и посмотрите, получается ли связный текст.
** 14. Ну и нужна заточенная дискуссия (Антон).
*** Comment
Над дискуссией поработали в текущей версии. Она не идеальна, но у меня нет идей, что мы можем с ней ещё сделать.
Я над ней думал достаточно долго, но кроме примера про Kotlin ничего так и не пришло. Буду рад выслушать предложения.
*** (Антон) Решение
Заход про то, что новые языки появляются и им нужны модели.
Указать языки, у которых ещё нет моделей памяти. Зачем нужно уточнять существующие модели.
** 15. Также надо пересмотреть заключение (Антон).
*** Comment
Над заключением ещё поработаю. У Вас есть конкретные к нему предложения/замечания?
*** (Антон) Решение
?Modeling Checking?
Расширение на release/acquire JS
Дискуссия и высказывание авторов
* Ideas for future work
** A set of litmus tests distinguishing observed models
