* Обсуждение
** Trace preserving выполняется для всех axiomatic memory models
** RMW отмечено как отсутствующее Java и MRD. Как так?
** В табличке нет модели SC
** Вероятно помимо conclusion нужен discussion, в котором будет проведён анализ моделей
** Что должно быть в анализе? Trade-offs, применимость в зависимости от ситуации, ...?
** Performance моделей. Стоит как-то более явно обсуждать его в таблице/статье. Как?
** Добавить Coherence
* Задачи
** TODO Написать conclusion, чтобы было понятно к чему мы идём
В conclusion нужно обрисовать ландшафт для дальнейших исследований в области.
*** Дальнейшие направления исследований
**** Mixed-size
**** Global Optimizations
**** Сравнение производительности
** TODO Отметить C++ компиляцию в ARMv8 как оптимальную
** TODO В future work упомянуть NVM модели и модели файловых систем 
** TODO Поправить табличку
*** исправить название моделей Weakest --> Weakestmo, RMD --> MRD
** TODO Background
*** Compilation scheme
**** Оптимальность (определение)
**** Заход на разные access modes
**** Перенести syntax deps в OOTA
*** DRF
**** internal/external --- LB+ctrl example
*** Semantics style
* Комментарии ДВ
** 1. Related work - мало.
Тут под видом related work можно было бы дать более широкий разворот существующей картины исследований, тенденций и показать,
что назрела необходимость обозрить programming languages weal memory models.
При этом во введении объясняется, что есть слабые модели памяти и мотивируется, что нужен какой-то общий обзорный труд про них.
Так дайте же в related works некоторую перспективу исследований в этой области. Еще раз повторюсь, чтобы показать, что есть что описывать.
*** ?Решение
Добавить пару абзацев про то, что существуют разные модели/подходы --- в некотором смысле сжатый вариант раздела 6.
Возможно, эта информация (но в ещё более сжатом виде) должна появиться во введении --- пока там слишком формально в одном месте цитируется 15 работ.

** 2. В методологии reseach question выглядит голо.
Нет объяснений и даже попыток их дать. "Это так" - пишет автор. И дальше поясняет, что это означает.
А к чему это так, почему обзор удобно строить вокруг этого question - остается загадкой.
Ну и дальше, до описания процедуры, все как-то несвязно – предлагается читателю самому, изнутри области, связывать заявления автора.
А необходимо все называть явно, пробрасывать мостики явно.    
*** ?Решение
Добавить абзац, подводящий к research question.
В нём (?на примере пары конкретных моделей?) указать, что модели памяти должны балансировать между слабостью и гарантиями.
Проблема в том, что это уже так или иначе упоминается во введении, нужно это учесть.
** 3. «10 peer-reviewed research papers [2, 5–7, 9, 12–16]
   whose main contribution was a proposal of a new PL weak memory model.» - это недостаточная и не та мотивация, как мне кажется.
   Вот если сказать, что они взяты с PLDI и POPL, и предлагают новые модели памяти, то это выглядит солиднее.
*** ?Решение
Добавить упоминание, что статьи опубликованы на PLDI и POPL.
** 4. Далее, keyword phrases лучше дать через запятую, не булетами. Помпезно и излишне раздуто выглядит.
   И, кстати, Женя, Вам это свойственно в данной статье. (у меня сходное впечатление от начала раздела про Методологию).    
*** Комментарий
(Антон) Мне больше нравится так, как есть. Не вижу проблемы.
** 5. Название раздела 4 «Criteria for Memory Models». Я не уверен в своем английском, но так говорят?
   Кретерий выбора, критерий чего-то (в смысле для чеого-то). А тут, по мне, лучше выглядело бы что то из этого списка «characteristics», «properties», «features».
*** Комментарий
(Антон) Criteria -- множественное число. В таком варианте нравится больше, чем предложенные варианты.
** 6. Более того, не объясняется, что это за феномен – критерий, и зачем он нужен. А сразу говорится, какие они, и поскакали в глубину.
   Нельзя сказать что-то вроде того, что речь идет об основных характеристиках слабых моделей, зачем нам нужны эти характеристики.
   Ну и дальше, что мы в качестве таковых выбрали вот такой список.
   И обязательно  объяснить, почему мы выбрали именно их. И получится более объемный текст в начале раздела.
   А то выходит, Женя, что Вы как-то формально отнеслись к своему предложению такие введения писать в начале каждого раздела.    
** 7. Можно, кстати,  прямо здесь дать отдельную табличку с этими критериями – у них же есть подкритерии! А то нефига не дружественно для читателя получается – Вы сразу его окунаете в детали, и нет места, где все собрано вместе (с мотивацией и общими объяснениями) про эти критерии.
** 8. В разделе 5, в начале, я нашел очень хороший объясняющий текст (редкость, кстати, в нашей статье!):
«A particular challenge of this comparison was the fact that consulted
research papers often use different terminology,
have incomplete information about models, and
sometimes they even contradict each other.»
 
Так вот, предлагаю перенести его во введение. А то там как-то пусто в смысле отточености мотивации. Нет обзоров и все… Ну а здесь парой слов восстановить это контекст и двигаться дальше.
** 9.  Порядок, в котором классы моделей упоминаются в первый раз в разделе 5, порядок следования этих классов в таблице и порядок соответствующих подразделов в разделе 6 ДОЛЖНЫ СОВПАДАТЬ! А сейчас они не совпадают…
** 10. Классов 6, а подразделов в разделе 6 – семь штук! Это все надо очень четко объяснять во введении к разделу.
** 11. Во введении к разделу 6 есть странный текст
«Note that we present the classes in different order
compared to the order in tables 1 and 2. It is
because we wanted to first discuss the problem
of thin-air values (§6.3) and then describe various
solutions of this problem (§6.4 to §6.6).»
 
Все запутывает. В целом, это введение надо начинать со структуры, а не с объяснений. Вот уже второе предложение этого введения должно отвечать на вопрос, почему разделов 7 а не 6.   
 
Структура у Вас Женя, тонко не проводится по тексту, но частенько теряется в объяснениях.
** 12.  В разделе 7 надо явно сказать, что мы лезем внутрь классов. Почему не говорите этого явно, прямо в первом предложении?
** 13. Женя, предлагаю тест. Вытащите все введения к разделам в отдельный файл, пустите их подряд и посмотрите, получается ли связный текст.
